services:
  db:
    image: postgres:16
    container_name: evently_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evently
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: evently_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: evently_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c 'alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000'

volumes:
  pgdata:
